### ISSUE TITLE
In votation_detail.html: two columns are missing from group votations table

### ISSUE THREAD

**Issue by ghost** [openpolis/open_municipio#103]
Columns "assenti" and "in missione" are missing from group votations table (which is the first table you encounter on main column).

**Comment by lorenzo-pasa** [comment]
"In missione" means nothing in the Comune's logic, so the column was deleted.

The column "assenti" is still missing, because in the template at [line 88](https://github.com/openpolis/open_municipio/blob/dev/open_municipio/templates/votations/votation_detail.html#L88) the `{{ group_vote.n_absent }}` variable must be corrected in `{{ group_vote.n_absents }}` and at [line 98](https://github.com/openpolis/open_municipio/blob/dev/open_municipio/templates/votations/votation_detail.html#L98) the `{{ votation.n_absent }}` variable must be corrected in `{{ votation.n_absents }}`, to match the fields in the models.
