### ISSUE TITLE
Define a versioning scheme for OM-XML schema

### ISSUE THREAD

**Issue by soujiro86** [openpolis/open_municipio#125]

**Comment by seldon** [comment]
Some refs: http://stackoverflow.com/questions/2014237/what-are-the-best-practices-for-versioning-xml-schemas

**Comment by fspegni** [comment]
Proposed solution:
- use "version" attribute in the schema file: <xs:schema ... version="X.Y">
- insert in the root element of a schema instance a version attribute (e.g. <OpenMunicipio ... schemaVersion="X.Y">)
- let the minor version ID (Y) to change when the schema is extended (e.g. new optional attributes and elements are added, ...)
- let the major version ID (X) to change when more substantial changes are made (e.g. new mandatory attributes and elements are added, or some are deleted ...) 
- implement in the importation logic a check of the instance-version vs. the schema version: if the major ID (X) differs, raise an importation error. if the minor ID (Y), then import as before and provide (suitable) default values for the "missing" attributes/elements (NB the incompatibility in major/minor version IDs are detected only at the importation side, i.e. OpenMunicipio servers ...)
- let the targetNamespace change when no change is made but the semantics of the elements changes (NB this allows the incompatibility to be detected directly from the provider, because the XML validator won't validate the instance with the schema) 

Worst practice:
- change the schema name/location: it is seen as the worst possible option because does not give any clue on the reason why previously valid documents, suddenly stop to validate.

Comments are welcome

**Comment by fspegni** [comment]
the approved approach is:
- public the import/export schema in a path like:

http://www.openmunicipio.it/1/OM-XML.xsd [UNOFFICIAL URL!!!]

note that:
- minor changes (i.e. adding optional elements/attributes) don't require a new schema version
- major changes (i.e. deleting elements/attributes, changing elements/attributes semantics) require a new schema version
- there is no need to maintain a minor-version number (minor versions would be needed to signal minor changes, but by definition our minor changes are only those that are backward compatible)
