### ISSUE TITLE
Replace ``ChargeXRef`` element with ``ActSubscriber``

### ISSUE THREAD

**Issue by seldon** [openpolis/open_municipio#143]
Within act-related OM-XML instances, `ActSubscribers` element should contain `ActSubscriber` elements, not `ChargeXRef`ones (see also #140)

**Comment by fspegni** [comment]
for now the ActSubscriber element contains only a chargeID attribute. should we move the "type" attribute from the element ActSubscribers to the newly create ActSubscriber? this perhaps would make the specification more intuitive (and only one ActSubscribers root element would be needed, instead of two: one with type "first subscriber" and one with type "co-signer")
