### ISSUE TITLE
Act and Vote can be set as key-act and key-vote

### ISSUE THREAD

**Issue by guglielmo** [openpolis/open_municipio#40]
It must be possible to state that an act or a vote is more important than others (key status or priority).

This is done by editors, in the front end interface, where editors may assign the **key** status  to the item, or remove it.

**Comment by guglielmo** [comment]
Since the requirements (as specified in chapter 7 and 8 of the functionality doc), are very basic, it could be sufficient to implement the fields directly in the Act and Votation classes, respectively, without resorting to a generic relations.

A **priority** field, with a default value of 0 could do both for Act (priorities) and Votation (is key or not).
As for Votation, a priority of 1 indicates that the Votation is to be considered a key one.

**Comment by fspegni** [comment]
Lorenzo P. and I are working on this aspect. Before starting to code, we need to have some added info on the specifications. In order to clarify them we identified the following possible scenarios, where an EDITOR (i.e. a privileged user) is using the site (both the front-end and the back-end):

```
1. front-end pages: 
    * the editor can bookmark/unbookmark an act/votation clicking on a star that appears in front of the act/votation title; the star is full black (full star) if the object is already a key-object, otherwise the star body is white while its border is black (empty star)
    * the editor can search an act/votation using the (specialization of) List views. When listing the titles of the found objects, a star appears in front of the titles of the objects themselves. The star is empty if the object is not flagged as key-object, and full otherwise

2. back-end pages:
    * when editing an act/votation a star appears that is empty when the object is not a key-object, and full otherwise
    * a page showing a list of acts/votations is shown, and before of every title a star is shown that is empty when the object is non-key, and full otherwise
```

Note that the stars in the front-pages are editable only to the editors, while non-privileged users can't click on the stars (but can visualize them).

What scenarios should we focus on? With what priority? Also: when clicking on a star, should the object be tagged immediately or should a confirmation be requested as well (e.g. via javascript or ajax)? An "intermediate" solution may be adopted: when changing the flag of an act/votation a notification can be shown on the screen to the editor while the object is immediately updated, and the modification can be considered effective only after some hours. This seems the most complicate and difficult implementation, perhaps not needed in this moment.

The decision about notification/confirmation aspects can be very important if the action of flagging an act/votation can generate news or emails on followers pages.

**Comment by lorenzo-pasa** [comment]
I think the notification/confirmation is strongly needed to avoid wrong caused-by-distraction bookmarking (e.g., the editor scrolling the list of all Acts, want to visit the single Act's page and click the star near the title of the Act instead the title).
But both choice has a downside:
- **notification** (skype style): the Editor is informed that he has just bookmarked an Act, but the news/mail about the Act's bookmarking is already generated (causing spam and wrong informations among the community)
- **confirmation** (via pop-up): it's more difficult to bookmark by mistake an Act, but the pop-up doubles the number of mouse's clicks needed to bookmark an Act (one click for the star, one click for the pop-up).

Maybe the right solution is a time-based solution (as Francesco wrote above). I only want to say that a check on news' generation can be very useful, whatever way we'll take.

**Comment by guglielmo** [comment]
Since acts/votes flagging do not generate any news, I would avoid any notification/confirmation mechanism.
I would implement the frontend interface mechanism, as described by Francesco:
- both the single act and the act in a list shows the stars, 
- only editors can turn the stars on and off
