### ISSUE TITLE
Duplicate user names displayed within monitoring box

### ISSUE THREAD

**Issue by seldon** [openpolis/open_municipio#45]
When a user issues multiple requests to monitor the same object, his/her name is listed multiple times among the set of users which are monitoring that object.

To reproduce this issue, follow these steps:
- go to e.g. `acts/1/`
- log in
- press the button "Avvia il monitoraggio" multiple times

**Comment by guglielmo** [comment]
This only happens when logged user has no profile associated, i.e. for the admin or editor users in the fixtures.
Registered users, have a profile and a press on the "Avvia il monitoraggio" button reload the page, showing the new button "Interrompi il monitoraggio".

Either admin and editor users get an associated profile, or they are not allowed to login in the frontend.

**Comment by seldon** [comment]
I'm not sure to understand what do you mean with the phrase _Either admin and editor users get an associated profile, or they are not allowed to login in the frontend_: it's a statement or a proposal ? 

In other words,  are you suggesting to _either_ associate a profile with staff users _or_ to deny frontend login to them ?
